services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password123!
      - MSSQL_PID=Express
    networks:
      - flyway-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P password123! -Q 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 10

  flyway:
    image: flyway/flyway:10
    container_name: flyway
    command: -url="jdbc:sqlserver://sqlserver:1433;databaseName=master;encrypt=false" -user=sa -password=password123! -locations=filesystem:/migrations migrate
    volumes:
      - ./TeamSpace.Database/Migrations:/migrations
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - flyway-network

  api:
    build:
      context: TeamSpace.Middleware
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TeamSpace;User Id=sa;Password=password123!;Encrypt=False;TrustServerCertificate=True
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    networks:
      - flyway-network

networks:
  flyway-network:
    driver: bridge