USE TeamSpace;
GO

CREATE TABLE Roles (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL
);

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    RoleId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

CREATE TABLE Spaces (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL,
    Description TEXT,
    Owner UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (Owner) REFERENCES Users(Id)
);

CREATE TABLE SpaceUserRelations (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    SpaceId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (SpaceId) REFERENCES Spaces(Id),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Notes (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Title NVARCHAR(100) NOT NULL,
    Content TEXT,
    SpaceId UNIQUEIDENTIFIER NOT NULL,
    CreatedBy UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (SpaceId) REFERENCES Spaces(Id),
    FOREIGN KEY (CreatedBy) REFERENCES Users(Id)
);