USE TeamSpace;
GO

ALTER TABLE Roles
ADD CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    ModifiedAt DATETIME2 NULL;
GO

ALTER TABLE Users
ADD CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    ModifiedAt DATETIME2 NULL;
GO

ALTER TABLE Spaces
ADD CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    ModifiedAt DATETIME2 NULL;
GO

ALTER TABLE SpaceUserRelations
ADD CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    ModifiedAt DATETIME2 NULL;
GO

ALTER TABLE Notes
ADD CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    ModifiedAt DATETIME2 NULL;
GO