#!/bin/bash

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

PATTERN="^(feat|fix|docs|style|refactor|test|chore|Mergeback): .+"

if [[ ! $COMMIT_MSG =~ $PATTERN ]]; then
    echo "❌ ERROR: Mensaje de commit inválido."
    echo "Debe seguir el formato: feat: mensaje, fix: mensaje, docs: mensaje, styles: mensaje."
    exit 1  # Cancela el commit
fi

echo "✅ Mensaje de commit válido."
exit 0  # Permite el commit
