name: Building Middleware

on:
  push:
    paths:
      - 'TeamSpace.Middleware/**'
  workflow_dispatch:

jobs:
  build:
    name: Building .NET Middleware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore TeamSpace.Middleware/TeamSpace.Middleware/TeamSpace.Middleware.csproj

      - name: Build
        run: dotnet build TeamSpace.Middleware/TeamSpace.Middleware/TeamSpace.Middleware.csproj